package com.convertidorxml.ui;


import com.convertidorxml.ctrl.Conformar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

public class frmProcess extends javax.swing.JDialog {

    private String path;
    private final boolean filtro;
    private final String usuario;
    private final String clave;
    private final String claveSOAP;
    
    

    public frmProcess(String path, boolean filtro, String usuario, String clave, String claveSOAP) {
        super(new JDialog(), false);
        initComponents();

        this.path = path;
        this.filtro = filtro;
        this.usuario = usuario;
        this.clave = clave;
        this.claveSOAP = claveSOAP;

        // Mostrar fromulario en el centro de la pantalla
        setLocationRelativeTo(null);

        // Cargando imagenes
        lb_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spiner.gif")));
        lb_gif.setVisible(true);

        // Ejecutando proceso
        new Worker().execute();
    }

    /**
     * Worker - Ejecutor de tareas
     */
    private class Worker extends SwingWorker<Integer, Void> {

        public Worker() {
        }

        @Override
        protected Integer doInBackground() throws Exception {
            GenerarXMls();
            return 0;
        }
    }

    /**
     * Método - Generar PDF
     */
    public void GenerarXMls() {
        try {
            
                Conformar c = new Conformar();
                
                String grupoPadre = "";
                int codMarca = -1;
                int campos = 1;
                int formatoXML = 2;

                String nombreCarrito = "";
                String filtroProducto = "";
                String filtroEcGarantia = "";

                String nuevos = "";
                String enLiquidacion = "";
                int soloModificadosDesde = 0;
                int ordenado = 0;

                c.setUsuario(usuario);
                c.setClave(clave);
                c.setUsuarioSOAP(claveSOAP);
                c.setGrupoPadre(grupoPadre);
                c.setCodMarca(codMarca);
                c.setCampos(campos);
                c.setFormatoXML(formatoXML);
                c.setNombreCarrito(nombreCarrito);
                c.setFiltroProducto(filtroProducto);
                c.setFiltroEcGarantia(filtroEcGarantia);
                c.setNuevos(nuevos);
                c.setEnLiquidacion(enLiquidacion);
                c.setSoloModificadosDesde(soloModificadosDesde);
                c.setOrdenado(ordenado);
              
                c.conformarXMLs(filtro,path);
                this.dispose();
                System.exit(0); 
            
        } catch (Exception ex) {
            System.out.println("error : "+ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error inesperado, por favor revise la información configurada."+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_process = new javax.swing.JLabel();
        lb_gif = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_process.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_process.setText("Procesando solicitud, por favor sea paciente...");
        lb_process.setAlignmentY(0.0F);

        lb_name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lb_name.setText("Generando XML");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_gif, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lb_process)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_process, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gif, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_gif;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_process;
    // End of variables declaration//GEN-END:variables
}
